executable = exe.sh
arguments = $(state)
should_transfer_files = YES
transfer_input_files =/afs/cern.ch/user/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/condor/WWG_Module.py,/afs/cern.ch/user/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/condor/WWG_postproc.py,/afs/cern.ch/user/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/condor/WWG_keep_and_drop.txt,/afs/cern.ch/user/y/yian/work/GZ/CMSSW_10_6_20/src/PhysicsTools/NanoAODTools/WWG/2017/condor/WWG_output_branch.txt
output                = out/WWg.$(ClusterId).$(ProcId).out
error                 = err/WWg.$(ClusterId).$(ProcId).err
log                   = log/WWg.$(ClusterId).log

# Send the job to Held state on failure.
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 3) && ((CurrentTime - EnteredCurrentStatus) > 600)
+JobFlavour = "tomorrow"

queue state from file.txt
